### ISSUE TITLE
Add some verbose while uploading

### ISSUE THREAD

**Issue by jcohenadad** [exmakhina/distriploy#14]
Currently there is no verbose. The program runs for 30s and we have no idea what's happening. It would be useful to display stuff like "Uploading zip to Github", etc.

**Comment by alexfoias** [comment]
@jcohenadad Sorry missed this issue. Should I spend some time on this issue ? Are we still using distriploy ?

**Comment by jcohenadad** [comment]
> Should I spend some time on this issue ? Are we still using distriploy ?

yes pls
