### ISSUE TITLE
Replace " by ' for listing URLs

### ISSUE THREAD

**Issue by jcohenadad** [exmakhina/distriploy#3]
(minor issue)

To follow our double/single quote [conventions](https://github.com/neuropoly/spinalcordtoolbox/wiki/Single-or-double-quotes), it would be nice for the final printout to replace " with ' to list URLs.

**Comment by zougloub** [comment]
Well, the printout is JSON (which happens to be Python-compatible), and also, in my SCT PR I used double-quotes (I had black'ed the section of source code around the URLs).
Also note that I intended for this software to not be SCT-specific.

But we could use an option for formatting the printout...

**Comment by jcohenadad** [comment]
that's fine, we have better to do with our time
